menu:
    # 首页: /
    博文: /archives/
    开发技巧: /categories/开发技巧/
    Springboot: /categories/Springboot/
    Java 新特性: /categories/Java-新特性/
    源码分析: /categories/Java-源码分析/
    GitHub: https://github.com/niumoo
    Rss: /atom.xml

toc: false
# favicon: /favicon.png
# logo: /favicon.png
favicon: /head.jpg
logo: /head.jpg

# Comment
# e.g disqus: seansun
disqus: xxx
duoshuo:
valine:
    appId: xxx
    appKey: xxx
    tip: 进来玩啊～～


# Analytics
# google-analytics:
ga: xxx

# Copyright Infomation
startyear: 2018
beian:xxx
feedback: xxx@126.com

